// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { compose } from "./compose.js";
import { diff } from "./diff.js";
import { invert } from "./invert.js";
import { isEqual } from "./isEqual.js";
import { transform } from "./transform.js";

export const OpAttributes = {
    compose,
    diff,
    invert,
    isEqual,
    transform,
}
