// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { compose } from "./compose.js";
import { diff } from "./diff.js";
import { invert } from "./invert.js";
import { transform } from "./transform.js";

type OpAttributes = Record<string, unknown>

type NullableOpAttributes<T> = { [K in keyof T]?: T[K] | null }

declare namespace OpAttributes {
    export {
        compose,
        diff,
        invert,
        transform,
    }
}

export {
    OpAttributes,
    NullableOpAttributes,
}
