// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { batch } from "./batch.js";
import { chop } from "./chop.js";
import { clean } from "./clean.js";
import { compose } from "./compose.js";
import { concat } from "./concat.js";
import { diff } from "./diff.js";
import { equals } from "./equals.js";
import { insert } from "./insert.js";
import { invert } from "./invert.js";
import { length } from "./length.js";
import { Op } from "../Op/index.js";
import { push } from "./push.js";
import { remove } from "./remove.js";
import { retain } from "./retain.js";
import { slice } from "./slice.js";
import { transform } from "./transform.js";

type Delta = Op[]

declare namespace Delta {
    export {
        batch,
        chop,
        clean,
        compose,
        concat,
        diff,
        equals,
        insert,
        invert,
        length,
        push,
        remove,
        retain,
        slice,
        transform,
    }
}

export {
    Delta,
}
