// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { Delta } from "../Delta/index.js";
import { hasNext } from "./hasNext.js";
import { next } from "./next.js";
import { peek } from "./peek.js";
import { peekLength } from "./peekLength.js";
import { peekType } from "./peekType.js";
import { rest } from "./rest.js";

interface OpIterator {
    index: number
    offset: number
    ops: Delta
}

declare namespace OpIterator {
    export {
        create,
        hasNext,
        next,
        peek,
        peekLength,
        peekType,
        rest,
    }
}

export {
    OpIterator,
}
