// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { hasNext } from "./hasNext.js";
import { next } from "./next.js";
import { Op } from "../Op/index.js";
import { OpAttributes } from "../OpAttributes/index.js";
import { peek } from "./peek.js";
import { peekLength } from "./peekLength.js";
import { peekType } from "./peekType.js";
import { rest } from "./rest.js";

interface OpIterator<T extends OpAttributes> {
    index: number
    offset: number
    ops: readonly Op<T>[]
}

declare namespace OpIterator {
    export {
        create,
        hasNext,
        next,
        peek,
        peekLength,
        peekType,
        rest,
    }
}

export {
    OpIterator,
}
