// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { length } from "./length.js";
import { OpAttributes } from "../OpAttributes/index.js";

type EmbedValue = Record<string, unknown>

type InsertOp = {
    insert: string | EmbedValue
    attributes: OpAttributes | undefined
}

type RetainOp = {
    retain: number
    attributes: OpAttributes | undefined
}

type DeleteOp = {
    delete: number
    attributes?: undefined
}

type Op = InsertOp | RetainOp | DeleteOp

declare namespace Op {
    export {
        length,
    }
}

export {
    Op,
    DeleteOp,
    EmbedValue,
    InsertOp,
    RetainOp,
}
