// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { length } from "./length.js";
import { OpAttributes } from "../OpAttributes/index.js";

type EmbedValue = Record<string, unknown>

type InsertOp = {
    attributes: OpAttributes | undefined
    type: "insert"
    value: string | EmbedValue
}

type RetainOp = {
    attributes: OpAttributes | undefined
    type: "retain"
    value: number
}

type RemoveOp = {
    attributes: undefined
    type: "remove"
    value: number
}

type Op = InsertOp | RetainOp | RemoveOp

declare namespace Op {
    export {
        length,
    }
}

export {
    Op,
    EmbedValue,
    InsertOp,
    RemoveOp,
    RetainOp,
}
